name: CI_1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          sudo apt-get install cppcheck
          cppcheck --enable=all homework_1