name: CI_1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checking-out repository
        uses: actions/checkout@v2

      - name: Testing by cppcheck
        run: |
          sudo apt install cppcheck
          cppcheck -q --enable=all --inconclusive homework_1/
      
      - name: Testing by cpplint
        run: |
          sudo apt install python3-pip
          sudo pip install cpplint
          find homework_1/ -name '*.c' | xargs cpplint --filter=-build/include_subdir --linelength=120
      
      - name: Unit testing
        run: |
          sudo apt install libgtest-dev
          cd homework_1
          mkdir build
          cd build
          cmake ..
          make
          ./test_toys
      
      - name: Testing by valgrind
        run: |
          sudo apt install valgrind
          cd homework_1/build
          valgrind --leak-check=full ./test_toys
      
      - name: Checking-out coverage
        run: |
          sudo apt install lcov
          cd homework_1/build/CMakeFiles/toys.dir
          gcov toys.c.gcno
          lcov --capture --directory ./ --output-file toys.info
          cp toys.info ../../toys.info
          cd ../toy.dir
          gcov toy.c.gcno
          lcov --capture --directory ./ --output-file toy.info
          cp toy.info ../../toy.info
          cd ../my_string.dir
          gcov my_string.c.gcno
          lcov --capture --directory ./ --output-file my_string.info
          cp my_string.info ../../my_string.info
          cd ../..
          genhtml toys.info toy.info my_string.info --output-directory cov/
      
      - name: Saving covarage file
        uses: actions/upload-artifact@v2
        with:
          name: Coverage
          path: homework_1/build/cov/