name: CI_1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Testing by cppcheck
        run: |
          sudo apt-get install cppcheck
          cppcheck -q --enable=all --inconclusive homework_1/
      
      - name: Testing by cpplint
        run: |
          sudo apt install python3-pip
          sudo pip install cpplint
          find homework_1/ -name '*.c' | xargs cpplint --linelength=120
      
      - name: Testing by clang-tidy
        run: |
          sudo apt-get install clang-tidy
          clang-tidy homework_1/ --checks=clang-analyzer-*,-clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling